const JOIN = "JOIN";
const JOINED = "JOINED";
const DISCONNECT = "DISCONNECT";
const CODE_CHANGE = "CODE_CHANGE";
const CODE_SYNC = "CODE_SYNC";
const LEAVE = "LEAVE";


export { JOIN, JOINED, DISCONNECT, CODE_CHANGE, LEAVE, CODE_SYNC};
