const JOIN = "JOIN";
const JOINED = "JOINED";
const DISCONNECT = "DISCONNECT";
const CODE_CHANGE = "CODE_CHANGE";
const CODE_SYNC = "CODE_SYNC";
const LEAVE = "LEAVE";
const SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA = "SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA";


export { JOIN, JOINED, DISCONNECT, CODE_CHANGE, LEAVE, CODE_SYNC, SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA };
