const JOIN = "JOIN";
const CHECK_ROOM_FOR_SAME_NAME = "CHECK_ROOM_FOR_SAME_NAME";
const JOINED = "JOINED";
const DISCONNECT = "DISCONNECT";
const CODE_CHANGE = "CODE_CHANGE";
const CODE_SYNC = "CODE_SYNC";
const LEAVE = "LEAVE";
const SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA = "SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA";
const SELECT_DIFFERENT_LANGUAGE = "SELECT_DIFFERENT_LANGUAGE";
const RUN_CODE_TO_GET_OUTPUT = "RUN_CODE_TO_GET_OUTPUT";


export { 
    JOIN, 
    CHECK_ROOM_FOR_SAME_NAME,
    JOINED, 
    DISCONNECT, 
    CODE_CHANGE, 
    LEAVE, 
    CODE_SYNC, 
    SINGLE_USER_JOIN_AT_STARTING_GIVE_PREVIOUS_DATA,
    SELECT_DIFFERENT_LANGUAGE,
    RUN_CODE_TO_GET_OUTPUT
};
